FROM python:3.8-buster

RUN apt-get update && apt-get install -y libgl1-mesa-dev

RUN pip install \
        numpy==1.20.0 \
        opencv-python==4.5.1.48 \
        torch==1.7.0

COPY srrescycgan_code_demo /code
WORKDIR /code

ENTRYPOINT ["python", "infer.py"]
